### ISSUE TITLE
Axel stl file issue

### ISSUE THREAD

**Issue by ecasas6** [JustMakeAnything/HeliostatV2#1]
I'm following along with your project, cool idea.  I was looking at the 3d files and it looks like you uploaded an incomplete version of the axel.stl file.  The one uploaded, only has the insertion points for the ausleger on one side.  The axel in your video shows the insertion points in the middle and on the opposite side.

<img width="364" alt="Screenshot 2024-11-10 at 10 06 10 AM" src="https://github.com/user-attachments/assets/3e594394-eed8-4fc1-9f85-2e8a0f17bc50">
<img width="883" alt="Screenshot 2024-11-10 at 10 05 43 AM" src="https://github.com/user-attachments/assets/3da62834-294c-4af4-84b5-a46badfa2bba">

**Comment by JustMakeAnything** [comment]
Hello Edgar,

Thanks for your isssue report. This file is indeed not the intended one. I fixed it and pushed the correct one.

Best regards,
Martin

**Comment by ecasas6** [comment]
Thank you :)
